name: Release
on:
  push:
    tags:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  RINGCENTRAL_SERVER_URL: ${{ secrets.RINGCENTRAL_SERVER_URL }}
  RINGCENTRAL_CLIENT_ID: ${{ secrets.RINGCENTRAL_CLIENT_ID }}
  RINGCENTRAL_CLIENT_SECRET: ${{ secrets.RINGCENTRAL_CLIENT_SECRET }}
  INGCENTRAL_JWT_TOKEN: ${{ secrets.RINGCENTRAL_JWT_TOKEN }}
  RINGCENTRAL_SENDER: ${{ secrets.RINGCENTRAL_SENDER }}
  RINGCENTRAL_RECEIVER: ${{ secrets.RINGCENTRAL_RECEIVER }}


jobs:
  Create_Nuget:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and pack
      run: dotnet build --configuration Release
           dotnet pack --configuration Release --output ./output --no-build
    - name: Publish to NuGet
      uses: NuGet/nuget-push-action@v1
      with:
        nuget_key: ${{ secrets.NUGET_APIKEY }} # Make sure to set this secret in your repository settings
        nuget_package: './output/*.nupkg'