name: Generate Documentation

on:
  push:
    branches:
      - main # Change to your default branch
      - addDocs

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Sandcastle
        run: |
          wget https://github.com/EWSoftware/SHFB/releases/download/v2022.2.7.0/SHFBInstaller_2022.2.7.0.zip
          unzip SHFBInstaller_2022.2.7.0.zip
          sudo wine SHFBInstaller_2022.2.7.0/Setup.exe /s

      - name: Generate Documentation
        run: SandcastleConsole.exe /project:"./RingCentral.Net.WebSocket.shfbproj"

      - name: Copy documentation to docs directory
        run: mv ./Documentation/Output/HtmlHelp ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
